### ISSUE TITLE
installapplications doesn't fail gracefully when the [preflight] tag is missing from the json

### ISSUE THREAD

**Issue by squirke1977** [erikng/installapplications#31]
My json file was created using generatejson.py - which doesn't automatically include a [preflight] tag. When installapplications runs - it can pull down my json file, then crashes out...

Traceback (most recent call last):
  File "/Library/Application Support/installapplications/installapplications.py", line 707, in <module>
    main()
  File "/Library/Application Support/installapplications/installapplications.py", line 587, in main
    for item in iajson[stage]:
KeyError: 'preflight'

**Comment by rickheil** [comment]
Apparently I forgot to make a PR with my changes that add the tag... will do later today or tomorrow AM.

**Comment by erikng** [comment]
Addressed with https://github.com/erikng/installapplications/pull/32
